aur-fetch: export GIT_DIR immediately
Note: ignored by git clone

diff --git a/lib/aur-fetch b/lib/aur-fetch
--- a/lib/aur-fetch
+++ b/lib/aur-fetch
@@ -12,18 +12,6 @@ verbose=0 recurse=0 confirm_seen=0 pull_args=('--verbose')
 # empty tree object
 git_empty_tree=$(git hash-object -t tree /dev/null)
 
-git_clone_set_config() {
-    if git clone "$AUR_LOCATION"/"$1".git; then
-        # Show PKGBUILDs first. (#399)
-        git -C "$1" config diff.orderFile "$2"
-        # Only allow fast-forward fetches. (#552)
-        git -C "$1" config remote.origin.fetch 'refs/heads/*:refs/remotes/origin/*'
-    else
-        error '%s: %s: Failed to clone repository' "$argv0" "$1"
-        exit 1
-    fi
-}
-
 usage() {
     cat <<! | base64 -d
 ICAgICAgICAgICAgIC4tLX5+LF9fCjotLi4uLiwtLS0tLS0tYH5+Jy5fLicKIGAtLCwsICAs
@@ -92,20 +80,29 @@ if (( recurse )); then
 else
    printf '%s\n' "$@"
 fi | while read -r pkg; do
-    # clean up variables
-    unset GIT_DIR GIT_WORK_TREE
+    # Avoid issues with filesystem boundaries. (#274)
+    export GIT_DIR=$pkg/.git GIT_WORK_TREE=$pkg
 
     if ! [[ -e $pkg ]]; then
-        git_clone_set_config "$pkg" "$orderfile"
+        if ! git clone "$AUR_LOCATION"/"$pkg".git; then
+            error '%s: %s: Failed to clone repository' "$argv0" "$1"
+            exit 1
+        fi
+
+        # Show PKGBUILDs first. (#399)
+        git config diff.orderFile "$orderfile"
+
+        # Only allow fast-forward fetches. (#552)
+        git config remote.origin.fetch 'refs/heads/*:refs/remotes/origin/*'
 
         if (( confirm_seen )); then
-            git -C "$pkg" update-ref AURUTILS_SEEN HEAD
+            git update-ref AURUTILS_SEEN HEAD
 
             warning 'Marked new repository %s as seen' "$pkg"
             continue # skip diff logic
         else
             # Set marker to empty tree object.
-            git -C "$pkg" update-ref AURUTILS_SEEN "$git_empty_tree"
+            git update-ref AURUTILS_SEEN "$git_empty_tree"
 
             # This case may be handled differently from an existing repo where
             # the AURUTILS_SEEN ref does not exist; here, we know that the repo
@@ -114,10 +111,7 @@ fi | while read -r pkg; do
         fi
     else
         # Ensure a valid git repository. (#586)
-        if GIT_DIR=$(git rev-parse --resolve-git-dir "$pkg"/.git); then
-            # Avoid issues with filesystem boundaries. (#274)
-            export GIT_DIR GIT_WORK_TREE=$pkg
-        else
+        if ! git rev-parse --resolve-git-dir "$pkg"/.git; then
             # The original git rev-parse exit code on a malformed git
             # repository is 128, or EKEYREVOKED in errno.h.
             exit 1
