aur-build: do not run symlink in tmpdir
Prevents using sudoers rules for archbuild

diff --git a/lib/aur-build b/lib/aur-build
--- a/lib/aur-build
+++ b/lib/aur-build
@@ -172,10 +172,8 @@ fi
 # the below relies on the implicit mounting of file:// repositories
 # by arch-nspawn in devtools>=20190821. (#591)
 if (( chroot )); then
-    if [[ -x /usr/bin/archbuild ]]; then
-        ln -s /usr/bin/archbuild "$tmp"/"$chroot_prefix"-"$machine"-build
-    else
-        error '%s: /usr/bin/archbuild: permission denied' "$argv0"
+    if ! type -P "$chroot_prefix"-"$machine"-build >/dev/null; then
+        error '%s: %s: command not found' "$argv0" "$chroot_prefix"-"$machine"-build
         exit 1
     fi
 
@@ -269,10 +267,10 @@ while IFS= read -ru "$fd" path; do
         printf '%s\n' >&2 "Running custom command: ${build_cmd[*]}"
         env PKGDEST="$var_tmp" AUR_REPO="$db_name" AUR_DBROOT="$db_root" "${build_cmd[@]}"
     elif (( chroot )); then
-        # XXX: makechrootpkg arguments are _appended_ to defaults (-c -n)
-        # defined in extra-x86_64-build
+        # XXX: makechrootpkg arguments are appended to defaults (-c -n)
+        # defined in archbuild, instead of replaced
         printf '%s\n' >&2 "Running $chroot_prefix-$machine-build"
-        env PKGDEST="$var_tmp" "$tmp"/"$chroot_prefix"-"$machine"-build \
+        env PKGDEST="$var_tmp" "$chroot_prefix"-"$machine"-build \
             "${archbuild_args[@]}" -- -d "$db_root" "${makechrootpkg_args[@]}"
     else
         printf '%s\n' >&2 "Running makepkg ${makepkg_args[*]}"
